{"name": "test_get_title", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: \u001b[31mNone\napi-tests\\test_api_status.py:26 in test_get_title() -> with check.raises(AssertionError):\n\u001b[0m\n------------------------------------------------------------\nFailed Checks: 1", "trace": "FAILURE: \u001b[31mNone\napi-tests\\test_api_status.py:26 in test_get_title() -> with check.raises(AssertionError):\n\u001b[0m\n------------------------------------------------------------\nFailed Checks: 1"}, "attachments": [{"name": "stdout", "source": "ab0d103a-ab15-46a9-b3be-b8aaabe74438-attachment.txt", "type": "text/plain"}], "start": 1681896828141, "stop": 1681896829027, "uuid": "e491312a-94cf-4253-bd7f-b2680a4672c3", "historyId": "247888500e3d698638b8ec1dd6210063", "testCaseId": "87c340832193f86c7f73fc9348d4034a", "fullName": "api-tests.test_api_status.TestOrfium#test_get_title", "labels": [{"name": "parentSuite", "value": "api-tests"}, {"name": "suite", "value": "test_api_status"}, {"name": "subSuite", "value": "TestOrfium"}, {"name": "host", "value": "N-20N3PF141YQ9"}, {"name": "thread", "value": "38768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api-tests.test_api_status"}]}